### ISSUE TITLE
[Help]有办法只在局域网中使用图床么，图片存在本地文件夹内

### ISSUE THREAD

**Issue by jiajiala** [imsheet/imsheet#10]
因为obsidian一旦附件过多，开启时候就会占用大量cpu，所以只能将图片拿出放到图床
但是又不想利用网络存储，是否有可能将图片放在本地文件夹内，然后在局域网中利用图床的链接将图链接到MD中

**Comment by yamfeel** [comment]
可以在obsidian的设置中忽略文件目录，解决Obsidian检索文件，占用大量CPU资源：
`打开Obsidian设置 -  【文件与链接】 - 【忽略文件】 - 【管理】，选择附件文件夹进行忽略。`
